#!/usr/bin/env bash
# Script that prints Domain and SubDaomain 0f the web site

print_domain-subdomain () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 2 ]
then
	print_domain-subdomain "$2.$1" "$2"
else
	print_domain-subdomain "www.$1" "www"
	print_domain-subdomain "lb-01.$1" "lb-01"
	print_domain-subdomain "web-01.$1" "web-01"
	print_domain-subdomain "web-02.$1" "web-02"
fi
