#!/usr/bin/env bash
# Script that configures Nginx server to redirect /redirect_me to another page.

# Update package list and install nginx
sudo apt-get update
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '24i\    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload
