#!/usr/bin/env bash
# A script Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "s/server_name _;/&\n\terror_page 404 \/custom_404.html;/" /etc/nginx/sites-enabled/default
sudo sed -i '24i\    location /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\t\t\n}\n\t\terror_page 404             /404.html;\n' /etc/nginx/sites-available/default
sudo service nginx restart
