#!/usr/bin/env bash
# Install and configure HAproxy on the lb-01 server.
sudo apt update
sudo apt upgrade -y
sudo apt install haproxy -y
sudo sh -c 'echo "frontend lb-01
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 342174-web-01 100.25.41.164:80
    server 342174-web-02 100.26.18.184:80" > /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
