#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

cnt=1
while [ $cnt -le 10 ]
do
  if [ $cnt -eq 4 ]
  then
    echo bad luck
  elif [ $cnt -eq 8 ]
  then
      echo good luck
  else
      echo Best School
  fi
  ((cnt++))
done
